### ISSUE TITLE
Generate setting yaml if one not provided

### ISSUE THREAD

**Issue by juliancheal** [juliancheal/ManageIQ-Cli#1]

**Comment by juliancheal** [comment]
```
---
-
  miq_host:
  miq_user:
  miq_password:
- provider:
  name:
  region:
  credentials:
    userid:
    password:
```

Something along the lines of this.
